---
title: "Biofilm_23S_CommunityAnalyses"
author: "Anna Vincent"
date: "6/3/2019"
output: html_document
---

## iPak Function

```{r Library, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)

#install and load multiple R packages needed for analysis

ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE, repos='http://cran.us.r-project.org')
    sapply(pkg, require, character.only = TRUE)
}

# Package list.  Contains all needed packages as a this writing. To update, simply add new package name to the list!

packages <- c("ggplot2", 
              "plyr", 
              "reshape2", 
              "RColorBrewer", 
              "scales", 
              "grid",
              "VennDiagram",
              "bibtex",
              "vegan",
              "RAM",
              "tidyr",
              "Rmisc",
              "glue",
              "reshape",
              "reshape2",
              "lemon",
              "gapminder",
              "magrittr",
              "dplyr",
              "ggpubr",
              "gridExtra",
              "patternplot",
              "tibble",
              "gplots",
              "broom",
              "data.table",
              "devtools",
              "wesanderson")
ipak(packages)

```

## Load data into Rmarkdown

```{r Load data, include=FALSE,echo=FALSE,warning=FALSE}
Algae.df<-read.delim("Vincent23S.final.subsample.tax.UNDERSCORES_REMOVED.summary")
Algae.df<-Algae.df[,1:59]

pd=position_dodge(width = 0.4)
```

## Remove Chloroplasts --> forgot to do this in Mothur

```{r Remove Chloroplasts, echo=FALSE, warning=FALSE}

#Algae.df=Algae.df[Algae.df$taxon !="Chloroplast_ge",]

```

## Shannon Diversity

```{r Calculate Shannon Diversity, echo=FALSE, warning=FALSE}

#Interested in effects of site and substrate on sequenced communities
#Select only 1 taxa level using the "taxlevel" column in the dataset, then perform analysis

Algae.df$taxlevel=as.factor(Algae.df$taxlevel)
Algae.df.6=subset.data.frame(Algae.df, taxlevel==6, drop=TRUE)

Algae.Shannon.df<-Algae.df.6 %>% 
  subset(select=c(-taxlevel,-rankID,-taxon,-daughterlevels,-total)) %>%
  mutate_at(vars(Anna2001AZPA23S:Anna2061SPTC23S),funs(diversity(.,index="shannon"))) %>%
  gather(key="Sample",value="Diversity") %>%
  distinct(Sample,Diversity) %>% 
  separate(Sample, into=c("Run_Info","Site","Substrate","Rep","Gene"), sep=c(-7,-5,-4,-3))

Algae.Shannon.df$Run_Info=NULL
Algae.Shannon.df$Gene=NULL
Algae.Shannon.df$Site=factor(Algae.Shannon.df$Site,levels=c("AZ","MD","WA","HC","NB","SP"),labels=c("Arizona","Maryland","Washington","Higgins Creek","N Br Chicago R","Springbrook Creek"))
Algae.Shannon.df$Substrate=factor(Algae.Shannon.df$Substrate,levels=c("P","F","T"),labels=c("PVC","Foam","Tile"))

#Summarize Shannon Diversity by Site and Substrate
#Shannon summary among sites and substrates --> get means across reps

Alg.Shan.Div.Summary<-Algae.Shannon.df %>% 
  group_by(Site, Substrate) %>% 
  summarise(mean=mean(Diversity),se=(sd(Diversity)/sqrt(n())))

#Shannon summary for 3 substrates

Alg.Shan.Div.Summary.SUB<-Algae.Shannon.df %>% 
  group_by(Substrate) %>% 
  summarise(mean=mean(Diversity),se=(sd(Diversity)/sqrt(n())))

```

```{r Figure: Shannon Diversity, echo=FALSE, warning=FALSE}

#Shannon plot in COLOR

Algae.Shannon.Diversity=ggplot(Alg.Shan.Div.Summary, aes(x=Site,y=mean,fill=Substrate))+
  geom_bar(stat="identity", color="black", position=position_dodge())+
  ylab("Shannon Diversity (H')")+
  xlab("Site")+
  theme_classic()+
  theme(legend.position=c(.45,.9),
        legend.direction = "horizontal",
        legend.title=element_blank(),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12),
        axis.text.x = element_text(angle = 45, hjust=1),
        legend.text=element_text(size=12),
        plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(colour = "white", size=0.1),
        panel.grid.minor = element_line(colour = "white"),
        strip.background = element_blank(),
        strip.placement = "outside")+
  theme(axis.title.x=element_blank(),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"))+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position
  =position_dodge(0.9))

Algae.Shannon.Diversity

ggsave("Algae.Shannon.Diversity.jpeg", device = "jpeg", width = 11, height = 8.5, units = "in")

```

```{r Figure: Shannon Diversity BW, echo=FALSE, warning=FALSE}

#Shannon plot in BW

Algae.Shannon.Diversity.BW=ggplot(Alg.Shan.Div.Summary, aes(x=Site,y=mean,fill=Substrate))+
  geom_bar(stat="identity", color="black", position=position_dodge())+
  ylab("Shannon Diversity (H')")+
  xlab("Site")+
  theme_classic()+
  scale_fill_manual(values=c("#000000", "#C0C0C0", "#FFFFFF"))+
  theme(legend.position=c(.45,.9),
        legend.direction = "horizontal",
        legend.title=element_blank(),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12),
        axis.text.x = element_text(angle = 45, hjust=1),
        legend.text=element_text(size=12),
        plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(colour = "white", size=0.1),
        panel.grid.minor = element_line(colour = "white"),
        strip.background = element_blank(),
        strip.placement = "outside")+
  theme(axis.title.x=element_blank(),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"))+
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position
  =position_dodge(0.9))

Algae.Shannon.Diversity.BW

ggsave("Algae.Shannon.Diversity.BW.jpeg", device = "jpeg", width = 11, height = 8.5, units = "in")

```

```{r 1/2-way ANOVAs Shannon Diversity, echo=FALSE, warning=FALSE}

Algae.Shannon.aov<-aov(Diversity~Site*Substrate, data=Algae.Shannon.df)
summary(Algae.Shannon.aov)

```

## OTU Richness

```{r OTU Richness, echo=FALSE, warning=FALSE}

#Count # of unqiue taxa we have per sample (or OTUs, operational taxonomic units)
#Use custom function, look for values >0 in each row of dataset

Algae.df$taxlevel=as.factor(Algae.df$taxlevel)
Algae.df.6=subset.data.frame(Algae.df, taxlevel==6,drop=TRUE)
observationThreshold = 1 #set min number to count as OTU being present
OTU=apply(Algae.df.6[,6:59]>=observationThreshold, 2, sum,na.rm=T) #check by row to see if each taxa present or not
OTU.0=apply(Algae.df.6[,6:59],2,sum,na.rm=T)
list_to_df <- function(list_for_df) {
  list_for_df <- as.list(list_for_df)
  nm <- names(list_for_df)
  if (is.null(nm))
    nm <- seq_along(list_for_df)
  df <- data.frame(name = nm, stringsAsFactors = FALSE)
  df$value <- unname(list_for_df)
  df
}

#Convert list to data frame with custom function above

Algae.OTU.df=list_to_df(OTU)
Algae.OTU.df$value=as.numeric(Algae.OTU.df$value)
Algae.OTU.df=separate(Algae.OTU.df,name,into=c("Run_Info","Site","Substrate","Rep","Gene"), sep=c(-7,-5,-4,-3))
Algae.OTU.df$Run_Info=NULL
Algae.OTU.df$Gene=NULL
Algae.OTU.df$Site=factor(Algae.OTU.df$Site,levels=c("AZ","MD","WA","HC","NB","SP"),labels=c("Arizona","Maryland","Washington","Higgins Creek","N Br Chicago R","Springbrook Creek"))
Algae.OTU.df$Substrate=factor(Algae.OTU.df$Substrate,levels=c("P","F","T"),labels=c("PVC","Foam","Tile"))
colnames(Algae.OTU.df)[colnames(Algae.OTU.df)=="value"] <- "OTU_Richness"

#2-Way ANOVA on OTU Richness

Algae.OTU.aov<-aov(OTU_Richness~Site*Substrate, data=Algae.OTU.df)
summary(Algae.OTU.aov)

#OTU Summary

Algae.OTU.df.summary=summarySE(Algae.OTU.df,measurevar="OTU_Richness",groupvars=c("Site","Substrate"),na.rm=TRUE)
colnames(Algae.OTU.df.summary)[colnames(Algae.OTU.df.summary)=="value"] <- "OTU_Richness"

```

## Relative Abundance

```{r Cumulative Relative Abundance, echo=FALSE, warning=FALSE}
#Calculate relative abundance by taxa for each sample and plot stacked bars and a heatmap

theme_set(theme_classic(base_size = 18))
Algae.df.3=subset.data.frame(Algae.df, taxlevel==3,drop=TRUE) #taxlevel 3 is Class
sites=list(colnames(Algae.df.3[,6:59])) #get list of samples
total=list(colnames(Algae.df.3[,1]))

#Custom relative abudance function --> takes list of sites and the total column for each taxa and finds the relaive abundance of each taxa in each sample
rabund=function(sites){
  rabund=sites/Algae.df.3$total
  return(rabund)
}

Algae.rabund.df=rabund(Algae.df.3[,6:59])
Algae.rabund.df=cbind(Algae.df.3$taxon,Algae.rabund.df)

#dcast and melt are the modern equivalents of transposition.  they work really well until they don't.
Algae.rabund.df=dcast(melt(Algae.rabund.df,id.vars="Algae.df.3$taxon"),variable~Algae.df.3$taxon)
Algae.rabund.df=separate(Algae.rabund.df,variable,into=c("Run_Info","Site","Substrate","Rep","Gene"), sep=c(-7,-5,-4,-3))
Algae.rabund.df$Run_Info=NULL
Algae.rabund.df$Gene=NULL
Algae.rabund.df$Site=factor(Algae.rabund.df$Site,levels=c("AZ","MD","WA","HC","NB","SP"),labels=c("Arizona","Maryland","Washington","Higgins Creek","N Br Chicago R","Springbrook Creek"))
Algae.rabund.df$Substrate=factor(Algae.rabund.df$Substrate,levels=c("P","F","T"),labels=c("PVC","Foam","Tile"))

Algae.rabund.h=aggregate(Algae.rabund.df[,4:33],list(Algae.rabund.df$Site,Algae.rabund.df$Substrate),mean)
Algae.taxa=list(colnames(Algae.rabund.h[,3:32])) 
Algae.rabund.h=melt(Algae.rabund.h,id.vars=c("Group.1","Group.2"))#Metls columns together, makes one long list

colnames(Algae.rabund.h)[colnames(Algae.rabund.h)=="Group.1"] <- "Site"
colnames(Algae.rabund.h)[colnames(Algae.rabund.h)=="Group.2"] <- "Substrate"

write.csv(Algae.rabund.h, "Algae.rabund.h.csv")

```

```{r Relative Abundance by Site, echo=FALSE, warning=FALSE}

#Arizona Subset
Algae.rabund.AZ=filter(Algae.rabund.df, Site=="Arizona")
Algae.rabund.AZ$Site=NULL
Algae.rabund.AZ=aggregate(Algae.rabund.AZ[,3:32],list(Algae.rabund.AZ$Substrate),mean)
Algae.rabund.AZ=melt(Algae.rabund.AZ, id="Group.1")
Algae.rabund.AZ$Group.1=as.factor(Algae.rabund.AZ$Group.1)
colnames(Algae.rabund.AZ)[colnames(Algae.rabund.AZ)=="Group.1"] <- "Substrate"
colnames(Algae.rabund.AZ)[colnames(Algae.rabund.AZ)=="variable"] <- "Taxa"
colnames(Algae.rabund.AZ)[colnames(Algae.rabund.AZ)=="value"] <- "Relative_Abundance"
write.csv(Algae.rabund.AZ, "Algae.rabund.AZ.csv")

#Maryland Subset
Algae.rabund.MD=filter(Algae.rabund.df, Site=="Maryland")
Algae.rabund.MD$Site=NULL
Algae.rabund.MD=aggregate(Algae.rabund.MD[,3:32],list(Algae.rabund.MD$Substrate),mean)
Algae.rabund.MD=melt(Algae.rabund.MD, id="Group.1")
Algae.rabund.MD$Group.1=as.factor(Algae.rabund.MD$Group.1)
colnames(Algae.rabund.MD)[colnames(Algae.rabund.MD)=="Group.1"] <- "Substrate"
colnames(Algae.rabund.MD)[colnames(Algae.rabund.MD)=="variable"] <- "Taxa"
colnames(Algae.rabund.MD)[colnames(Algae.rabund.MD)=="value"] <- "Relative_Abundance"
write.csv(Algae.rabund.MD, "Algae.rabund.MD.csv")

#Washington Subset
Algae.rabund.WA=filter(Algae.rabund.df, Site=="Washington")
Algae.rabund.WA$Site=NULL
Algae.rabund.WA=aggregate(Algae.rabund.WA[,3:32],list(Algae.rabund.WA$Substrate),mean)
Algae.rabund.WA=melt(Algae.rabund.WA, id="Group.1")
Algae.rabund.WA$Group.1=as.factor(Algae.rabund.WA$Group.1)
colnames(Algae.rabund.WA)[colnames(Algae.rabund.WA)=="Group.1"] <- "Substrate"
colnames(Algae.rabund.WA)[colnames(Algae.rabund.WA)=="variable"] <- "Taxa"
colnames(Algae.rabund.WA)[colnames(Algae.rabund.WA)=="value"] <- "Relative_Abundance"
write.csv(Algae.rabund.WA, "Algae.rabund.WA.csv")

#Higgins Subset
Algae.rabund.HC=filter(Algae.rabund.df, Site=="Higgins Creek")
Algae.rabund.HC$Site=NULL
Algae.rabund.HC=aggregate(Algae.rabund.HC[,3:32],list(Algae.rabund.HC$Substrate),mean)
Algae.rabund.HC=melt(Algae.rabund.HC, id="Group.1")
Algae.rabund.HC$Group.1=as.factor(Algae.rabund.HC$Group.1)
colnames(Algae.rabund.HC)[colnames(Algae.rabund.HC)=="Group.1"] <- "Substrate"
colnames(Algae.rabund.HC)[colnames(Algae.rabund.HC)=="variable"] <- "Taxa"
colnames(Algae.rabund.HC)[colnames(Algae.rabund.HC)=="value"] <- "Relative_Abundance"
write.csv(Algae.rabund.HC, "Algae.rabund.HC.csv")

#N Branch Subset
Algae.rabund.NB=filter(Algae.rabund.df, Site=="N Br Chicago R")
Algae.rabund.NB$Site=NULL
Algae.rabund.NB=aggregate(Algae.rabund.NB[,3:32],list(Algae.rabund.NB$Substrate),mean)
Algae.rabund.NB=melt(Algae.rabund.NB, id="Group.1")
Algae.rabund.NB$Group.1=as.factor(Algae.rabund.NB$Group.1)
colnames(Algae.rabund.NB)[colnames(Algae.rabund.NB)=="Group.1"] <- "Substrate"
colnames(Algae.rabund.NB)[colnames(Algae.rabund.NB)=="variable"] <- "Taxa"
colnames(Algae.rabund.NB)[colnames(Algae.rabund.NB)=="value"] <- "Relative_Abundance"
write.csv(Algae.rabund.NB, "Algae.rabund.NB.csv")

#Springbrook Subset
Algae.rabund.SP=filter(Algae.rabund.df, Site=="Springbrook Creek")
Algae.rabund.SP$Site=NULL
Algae.rabund.SP=aggregate(Algae.rabund.SP[,3:32],list(Algae.rabund.SP$Substrate),mean)
Algae.rabund.SP=melt(Algae.rabund.SP, id="Group.1")
Algae.rabund.SP$Group.1=as.factor(Algae.rabund.SP$Group.1)
colnames(Algae.rabund.SP)[colnames(Algae.rabund.SP)=="Group.1"] <- "Substrate"
colnames(Algae.rabund.SP)[colnames(Algae.rabund.SP)=="variable"] <- "Taxa"
colnames(Algae.rabund.SP)[colnames(Algae.rabund.SP)=="value"] <- "Relative_Abundance"
write.csv(Algae.rabund.SP, "Algae.rabund.SP.csv")

```

##Non-metric Multidimensional Scaling (NMDS)

```{r NMDS, echo=FALSE, warning=FALSE}

Algae.df.sp=subset.data.frame(Algae.df, taxlevel==3, drop=TRUE) %>% 
  select(-taxlevel,-rankID,-daughterlevels,-total)
Algae.df.sp<-Algae.df.sp  %>% 
  gather(key="Sample",value="obs",-taxon) %>% 
  separate(Sample, into=c("Run_Info","Site","Substrate","Rep","Gene"), sep=c(-7,-5,-4,-3))
Algae.df.sp$"Gene"=NULL
Algae.df.sp$"Run_Info"=NULL

#Spread takes a tall data table and makes it wide --> each "key" value = a column populated by the "value"
Algae.df.sps<-Algae.df.sp %>%
  spread(key=taxon, value=obs)
#Combining Site, Substrate, and Rep - turn into row names
     Algae.df.sps$Sample <- paste(Algae.df.sps$"Site",Algae.df.sps$"Substrate",Algae.df.sps$"Rep", sep = "")
     Algae.df.sps<-data.frame(Algae.df.sps, row.names = 34)
     Algae.df.sps$"Site"=NULL
     Algae.df.sps$"Substrate"=NULL
     Algae.df.sps$"Rep"=NULL

Algae.ord.dist=vegdist(Algae.df.sps) #get distances
Algae.ord.nmds=metaMDS(Algae.ord.dist) #run NMDS
Algae.ORD=data.frame(MDS1=Algae.ord.nmds$points[,1],MDS2=Algae.ord.nmds$points[,2]) #exrtact NMDS coordinates
Algae.ORD.csv <- Algae.ORD %>% 
  rownames_to_column("Sample_Info")
Algae.ORD.csv=separate(Algae.ORD.csv,"Sample_Info",into=c("Site","Substrate","Rep"), sep=c(2,-1))
Algae.ORD.csv$Site=factor(Algae.ORD.csv$Site,levels=c("AZ","MD","WA","HC","NB","SP"),labels=c("Arizona","Maryland","Washington","Higgins Creek","N Br Chicago R","Springbrook Creek"))
Algae.ORD.csv$Substrate=factor(Algae.ORD.csv$Substrate,levels=c("P","F","T"),labels=c("PVC","Foam","Tile"))
write.csv(Algae.ORD.csv, file="Algae.ORD.csv")

```

```{r NMDS Plot, echo=FALSE, warning=FALSE}

Algae.NMDS=ggplot(Algae.ORD.csv)+
  geom_point(mapping= aes(MDS1,MDS2,shape=Site,color=Substrate,fill=Substrate))+
  coord_fixed(ratio=1)+
  ggtitle("Algal Communitites")+
  theme_classic()+
  labs(shape="Site",substrate="Substrate")

Algae.NMDS

ggsave("Algae.NMDS.jpeg", device = "jpeg", width = 11, height = 8.5, units = "in")

```

